# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to run the
# zipkin-elasticsearch container instead of the zipkin-mysql container.

version: '2'

services:
  # Switch storage type to Elasticsearch
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    environment:
      #- RABBIT_URI=amqp://admin:12345@localhost:5672/sleuth
      - RABBIT_ADDRESSES=192.168.100.240
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      # - ES_HOSTS=elasticsearch
      - ES_HOSTS=192.168.100.249
      # Uncomment to see requests to and from elasticsearch
      # - ES_HTTP_LOGGING=BODY
      - ES_HTTP_LOGGING=BASIC
